# Generated by Django 5.2.5 on 2025-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("artist", models.CharField(max_length=100)),
                ("genres", models.CharField(max_length=50)),
                ("ranking", models.IntegerField()),
                ("release_date", models.DateField()),
            ],
        ),
    ]
